### ISSUE TITLE
charades.json Not Found

### ISSUE THREAD

**Issue by Jayaprakash2k3** [ByZ0e/Glance-Focus#3]
Traceback (most recent call last):
  File "/kaggle/working/Glance-Focus/Glance-Focus/train_glance_focus_uns.py", line 352, in <module>
    train(args)
  File "/kaggle/working/Glance-Focus/Glance-Focus/train_glance_focus_uns.py", line 95, in train
    train_dataset = VideoQADataset(args.task_type, args.train_data_file_path.format(args.base_data_dir),
  File "/kaggle/working/Glance-Focus/Glance-Focus/dataset/star.py", line 141, in __init__
    with open(event_anno_file, 'rb') as f:  # TODO: PATH
FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/working/Glance-Focus/STAR/txt_db/charades.json'

**Comment by ByZ0e** [comment]
Please update the ''--event_anno_path'' from ''charades.json'' to ''events.json''. Actually, under the unsupervised version, this file will not be used, just for keeping the code consistency.
